image: { 
  file: .gitpod.Dockerfile 
}
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3333
    onOpen: ignore
  - port: 4040
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 19000
    onOpen: ignore
  - port: 19001
    onOpen: ignore
  - port: 19002
    onOpen: ignore  
tasks:
  - init: nvm install 13.3.0 && npm -g install yarn && npm -g install expo-cli
    command: cd backend && yarn install && yarn dev
    command: cd ../mobile && yarn install && expo start
    command: cd ../web && yarn install && yarn start

